version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysqlDB
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: dev
    ports:
      - "8888:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local