spring:
  # Database Setting Info (Database를 H2로 사용하기 위해 H2연결 정보 입력)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # mysql driver를 사용하겠다.
    url: jdbc:mysql://localhost:8888/dev?serverTimezone=Asia/Seoul
    username: root  # username 정보
    password: 1234 # password 정보
  ## JPA Setting Info
  jpa:
    hibernate:
      ddl-auto: update  # 테이블 생성 및 스키마 수정 옵션 설정
    properties:
      hibernate:
        ddl-auto: true # 기존 테이블 삭제 후 생성(필요 시 false 로 변경)
        show_sql: true  # sql 쿼리를 보여줌
        format_sql: true  # sql query formatting
        use_sql_comments: true  # sql 쿼리의 추가정보
        dialect: org.hibernate.dialect.MySQL8Dialect  # 사용할 Hibernate Dialect 설정
        use-new-id-generator-mappings: false

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace  # query의 ?에 어떤 값이 들어가는지 추적할 설정, TRACE Log에 값을 보여줌.